version: "3.3"

services:
  db:
    image: mysql/mysql-server:8.0.13
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=riskfactor
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - storage:/var/lib/mysql

volumes:
  storage:
