version: "2"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/riskfactor?createDatabaseIfNotExist=true&useSSL=false
    networks:
      - backend

  db:
    image: mysql/mysql-server:8.0.13
    restart: always
    command: ["--default-authentication-plugin=mysql_native_password", "--log-bin-trust-function-creators=ON"]
    environment:
      - MYSQL_DATABASE=riskfactor
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
    volumes:
      - storage:/var/lib/mysql
    networks:
      - backend

volumes:
  storage:

networks:
  backend:
